language: erlang
script: "make travis"
otp_release:
  - 18.2
  - 18.1
  - 18.0
  - 17.3
  - 17.1 
  - 17.0
  - R16B03-1
  - R16B
  - R15B03
  - R15B
before_script:
  - sudo service postgresql stop
  - sudo service mysql stop
  - sudo service memcached stop
